export const UPDATE_GAME = 'UPDATE_GAME';
export const GAME_OVER = 'GAME_OVER';
export const SET_TIME = 'SET_TIME';
export const PLAYER_BID = 'PLAYER_BID';
export const RESET_BIDS = 'RESET_BIDS';
export const SET_CURRENT_ITEM = 'SET_CURRENT_ITEM';

export const PLAYER_ENTER = 'PLAYER_ENTER';
export const PLAYER_LEAVE = 'PLAYER_LEAVE';
export const SET_PLAYER_BUDGET = 'SET_PLAYER_BUDGET';
export const PLAYER_PURCHASED_ITEM = 'PLAYER_PURCHASED_ITEM';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const RESET_MESSAGES = 'RESET_MESSAGES';